// spec21 v3 - 角色權限系統
// 6 角色：admin, manager, finance, cashier, purchasing, viewer

export const ROLE_CODES = {
  ADMIN: 'admin',
  MANAGER: 'manager',
  FINANCE: 'finance',
  CASHIER: 'cashier',
  PURCHASING: 'purchasing',
  VIEWER: 'viewer',
};

// 所有系統權限定義 (18 modules)
export const PERMISSIONS = {
  // 進貨
  PURCHASING_VIEW: 'purchasing.view',
  PURCHASING_CREATE: 'purchasing.create',
  PURCHASING_EDIT: 'purchasing.edit',
  // 發票
  SALES_VIEW: 'sales.view',
  SALES_CREATE: 'sales.create',
  SALES_EDIT: 'sales.edit',
  // 財務付款單
  FINANCE_VIEW: 'finance.view',
  FINANCE_CREATE: 'finance.create',
  FINANCE_EDIT: 'finance.edit',
  // 出納
  CASHIER_VIEW: 'cashier.view',
  CASHIER_EXECUTE: 'cashier.execute',
  CASHIER_REJECT: 'cashier.reject',
  // 庫存
  INVENTORY_VIEW: 'inventory.view',
  // 現金流
  CASHFLOW_VIEW: 'cashflow.view',
  CASHFLOW_CREATE: 'cashflow.create',
  CASHFLOW_EDIT: 'cashflow.edit',
  // PMS
  PMS_VIEW: 'pms.view',
  PMS_IMPORT: 'pms.import',
  // 貸款
  LOAN_VIEW: 'loan.view',
  LOAN_CREATE: 'loan.create',
  LOAN_CONFIRM: 'loan.confirm',
  // 支票
  CHECK_VIEW: 'check.view',
  CHECK_CREATE: 'check.create',
  CHECK_CLEAR: 'check.clear',
  // 對帳
  RECONCILIATION_VIEW: 'reconciliation.view',
  RECONCILIATION_CREATE: 'reconciliation.create',
  // 租屋
  RENTAL_VIEW: 'rental.view',
  RENTAL_CREATE: 'rental.create',
  RENTAL_EDIT: 'rental.edit',
  // 月結
  MONTHEND_VIEW: 'monthend.view',
  MONTHEND_EXECUTE: 'monthend.execute',
  MONTHEND_UNLOCK: 'monthend.unlock',
  // 年結
  YEAREND_VIEW: 'yearend.view',
  YEAREND_EXECUTE: 'yearend.execute',
  // 費用
  EXPENSE_VIEW: 'expense.view',
  EXPENSE_CREATE: 'expense.create',
  // 分析
  ANALYTICS_VIEW: 'analytics.view',
  // 匯出
  EXPORT_XLSX: 'export.xlsx',
  EXPORT_CSV: 'export.csv',
  EXPORT_PDF: 'export.pdf',
  // 稽核
  AUDIT_VIEW: 'audit.view',
  // 附件
  ATTACHMENT_UPLOAD: 'attachment.upload',
  ATTACHMENT_DELETE: 'attachment.delete',
  // 系統設定
  SETTINGS_VIEW: 'settings.view',
  SETTINGS_EDIT: 'settings.edit',
  // 使用者管理
  USER_MANAGE: 'user.manage',
  // 現金盤點 (spec26)
  CASH_COUNT_VIEW: 'cashcount.view',
  CASH_COUNT_CREATE: 'cashcount.create',
  CASH_COUNT_REVIEW: 'cashcount.review',
  // 資料備份 (spec27)
  BACKUP_VIEW: 'backup.view',
  BACKUP_EXECUTE: 'backup.execute',
  BACKUP_RESTORE: 'backup.restore',
  // 通知管理 (spec28)
  NOTIFICATION_VIEW: 'notification.view',
  NOTIFICATION_MANAGE: 'notification.manage',
  // 資料匯入 (spec25)
  IMPORT_EXECUTE: 'import.execute',
  // 列印 (spec23)
  PRINT_VOUCHER: 'print.voucher',
  // 工程會計 (營造：工程案、合約期數、材料)
  ENGINEERING_VIEW: 'engineering.view',
  ENGINEERING_CREATE: 'engineering.create',
  ENGINEERING_EDIT: 'engineering.edit',
};

// 各角色預設權限
export const ROLE_DEFAULTS = {
  [ROLE_CODES.ADMIN]: Object.values(PERMISSIONS),
  [ROLE_CODES.MANAGER]: [
    PERMISSIONS.PURCHASING_VIEW, PERMISSIONS.PURCHASING_CREATE, PERMISSIONS.PURCHASING_EDIT,
    PERMISSIONS.SALES_VIEW, PERMISSIONS.SALES_CREATE, PERMISSIONS.SALES_EDIT,
    PERMISSIONS.FINANCE_VIEW, PERMISSIONS.FINANCE_CREATE, PERMISSIONS.FINANCE_EDIT,
    PERMISSIONS.CASHIER_VIEW,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.CASHFLOW_VIEW, PERMISSIONS.CASHFLOW_CREATE,
    PERMISSIONS.PMS_VIEW, PERMISSIONS.PMS_IMPORT,
    PERMISSIONS.LOAN_VIEW, PERMISSIONS.LOAN_CREATE, PERMISSIONS.LOAN_CONFIRM,
    PERMISSIONS.CHECK_VIEW, PERMISSIONS.CHECK_CREATE, PERMISSIONS.CHECK_CLEAR,
    PERMISSIONS.RECONCILIATION_VIEW, PERMISSIONS.RECONCILIATION_CREATE,
    PERMISSIONS.RENTAL_VIEW, PERMISSIONS.RENTAL_CREATE, PERMISSIONS.RENTAL_EDIT,
    PERMISSIONS.MONTHEND_VIEW, PERMISSIONS.MONTHEND_EXECUTE,
    PERMISSIONS.YEAREND_VIEW, PERMISSIONS.YEAREND_EXECUTE,
    PERMISSIONS.EXPENSE_VIEW, PERMISSIONS.EXPENSE_CREATE,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.EXPORT_XLSX, PERMISSIONS.EXPORT_CSV, PERMISSIONS.EXPORT_PDF,
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.ATTACHMENT_UPLOAD, PERMISSIONS.ATTACHMENT_DELETE,
    PERMISSIONS.SETTINGS_VIEW,
    PERMISSIONS.CASH_COUNT_VIEW, PERMISSIONS.CASH_COUNT_CREATE, PERMISSIONS.CASH_COUNT_REVIEW,
    PERMISSIONS.NOTIFICATION_VIEW,
    PERMISSIONS.PRINT_VOUCHER,
    PERMISSIONS.ENGINEERING_VIEW, PERMISSIONS.ENGINEERING_CREATE, PERMISSIONS.ENGINEERING_EDIT,
  ],
  [ROLE_CODES.FINANCE]: [
    PERMISSIONS.PURCHASING_VIEW,
    PERMISSIONS.SALES_VIEW, PERMISSIONS.SALES_CREATE, PERMISSIONS.SALES_EDIT,
    PERMISSIONS.FINANCE_VIEW, PERMISSIONS.FINANCE_CREATE, PERMISSIONS.FINANCE_EDIT,
    PERMISSIONS.CASHIER_VIEW,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.CASHFLOW_VIEW, PERMISSIONS.CASHFLOW_CREATE, PERMISSIONS.CASHFLOW_EDIT,
    PERMISSIONS.PMS_VIEW, PERMISSIONS.PMS_IMPORT,
    PERMISSIONS.LOAN_VIEW, PERMISSIONS.LOAN_CREATE, PERMISSIONS.LOAN_CONFIRM,
    PERMISSIONS.CHECK_VIEW, PERMISSIONS.CHECK_CREATE,
    PERMISSIONS.RECONCILIATION_VIEW, PERMISSIONS.RECONCILIATION_CREATE,
    PERMISSIONS.RENTAL_VIEW, PERMISSIONS.RENTAL_CREATE, PERMISSIONS.RENTAL_EDIT,
    PERMISSIONS.MONTHEND_VIEW, PERMISSIONS.MONTHEND_EXECUTE,
    PERMISSIONS.YEAREND_VIEW, PERMISSIONS.YEAREND_EXECUTE,
    PERMISSIONS.EXPENSE_VIEW, PERMISSIONS.EXPENSE_CREATE,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.EXPORT_XLSX, PERMISSIONS.EXPORT_CSV, PERMISSIONS.EXPORT_PDF,
    PERMISSIONS.ATTACHMENT_UPLOAD, PERMISSIONS.ATTACHMENT_DELETE,
    PERMISSIONS.CASH_COUNT_VIEW, PERMISSIONS.CASH_COUNT_CREATE, PERMISSIONS.CASH_COUNT_REVIEW,
    PERMISSIONS.NOTIFICATION_VIEW,
    PERMISSIONS.PRINT_VOUCHER,
    PERMISSIONS.ENGINEERING_VIEW, PERMISSIONS.ENGINEERING_CREATE, PERMISSIONS.ENGINEERING_EDIT,
  ],
  [ROLE_CODES.CASHIER]: [
    PERMISSIONS.PURCHASING_VIEW,
    PERMISSIONS.SALES_VIEW,
    PERMISSIONS.FINANCE_VIEW,
    PERMISSIONS.CASHIER_VIEW, PERMISSIONS.CASHIER_EXECUTE, PERMISSIONS.CASHIER_REJECT,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.CASHFLOW_VIEW, PERMISSIONS.CASHFLOW_CREATE, PERMISSIONS.CASHFLOW_EDIT,
    PERMISSIONS.LOAN_VIEW,
    PERMISSIONS.CHECK_VIEW, PERMISSIONS.CHECK_CLEAR,
    PERMISSIONS.RECONCILIATION_VIEW,
    PERMISSIONS.RENTAL_VIEW,
    PERMISSIONS.MONTHEND_VIEW,
    PERMISSIONS.YEAREND_VIEW,
    PERMISSIONS.EXPENSE_VIEW,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.EXPORT_XLSX, PERMISSIONS.EXPORT_CSV,
    PERMISSIONS.ATTACHMENT_UPLOAD,
    PERMISSIONS.CASH_COUNT_VIEW, PERMISSIONS.CASH_COUNT_CREATE,
    PERMISSIONS.PRINT_VOUCHER,
    PERMISSIONS.ENGINEERING_VIEW,
  ],
  [ROLE_CODES.PURCHASING]: [
    PERMISSIONS.PURCHASING_VIEW, PERMISSIONS.PURCHASING_CREATE, PERMISSIONS.PURCHASING_EDIT,
    PERMISSIONS.SALES_VIEW,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.PMS_VIEW,
    PERMISSIONS.EXPENSE_VIEW,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.EXPORT_XLSX, PERMISSIONS.EXPORT_CSV,
    PERMISSIONS.ATTACHMENT_UPLOAD,
    PERMISSIONS.PRINT_VOUCHER,
    PERMISSIONS.ENGINEERING_VIEW, PERMISSIONS.ENGINEERING_CREATE, PERMISSIONS.ENGINEERING_EDIT,
  ],
  [ROLE_CODES.VIEWER]: [
    PERMISSIONS.PURCHASING_VIEW,
    PERMISSIONS.SALES_VIEW,
    PERMISSIONS.FINANCE_VIEW,
    PERMISSIONS.CASHIER_VIEW,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.CASHFLOW_VIEW,
    PERMISSIONS.PMS_VIEW,
    PERMISSIONS.LOAN_VIEW,
    PERMISSIONS.CHECK_VIEW,
    PERMISSIONS.RECONCILIATION_VIEW,
    PERMISSIONS.RENTAL_VIEW,
    PERMISSIONS.MONTHEND_VIEW,
    PERMISSIONS.YEAREND_VIEW,
    PERMISSIONS.EXPENSE_VIEW,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.EXPORT_CSV,
    PERMISSIONS.CASH_COUNT_VIEW,
    PERMISSIONS.NOTIFICATION_VIEW,
    PERMISSIONS.ENGINEERING_VIEW,
  ],
};

// 角色中文名稱
export const ROLE_LABELS = {
  [ROLE_CODES.ADMIN]: '系統管理員',
  [ROLE_CODES.MANAGER]: '主管',
  [ROLE_CODES.FINANCE]: '財務',
  [ROLE_CODES.CASHIER]: '出納',
  [ROLE_CODES.PURCHASING]: '採購',
  [ROLE_CODES.VIEWER]: '檢視者',
};

// 角色顏色
export const ROLE_COLORS = {
  [ROLE_CODES.ADMIN]: 'bg-red-100 text-red-800',
  [ROLE_CODES.MANAGER]: 'bg-blue-100 text-blue-800',
  [ROLE_CODES.FINANCE]: 'bg-indigo-100 text-indigo-800',
  [ROLE_CODES.CASHIER]: 'bg-amber-100 text-amber-800',
  [ROLE_CODES.PURCHASING]: 'bg-orange-100 text-orange-800',
  [ROLE_CODES.VIEWER]: 'bg-gray-100 text-gray-800',
};

/**
 * 檢查使用者是否擁有指定權限
 */
export function hasPermission(userPermissions, requiredPermission) {
  if (!userPermissions || !Array.isArray(userPermissions)) return false;
  // admin has all permissions
  if (userPermissions.includes('*')) return true;
  return userPermissions.includes(requiredPermission);
}

/**
 * 檢查使用者是否擁有任一指定權限
 */
export function hasAnyPermission(userPermissions, requiredPermissions) {
  if (!userPermissions || !Array.isArray(userPermissions)) return false;
  if (userPermissions.includes('*')) return true;
  return requiredPermissions.some(p => userPermissions.includes(p));
}

/**
 * 取得使用者的合併權限（從所有角色）
 */
export async function getUserPermissions(prisma, userId) {
  const userRoles = await prisma.userRole.findMany({
    where: { userId },
    include: { role: true },
  });

  const permSet = new Set();
  const roleCodes = [];

  for (const ur of userRoles) {
    roleCodes.push(ur.role.code);
    const perms = ur.role.permissions;
    if (Array.isArray(perms)) {
      perms.forEach(p => permSet.add(p));
    }
  }

  // admin 角色擁有所有權限
  if (roleCodes.includes(ROLE_CODES.ADMIN)) {
    return { roles: roleCodes, permissions: ['*'] };
  }

  return { roles: roleCodes, permissions: Array.from(permSet) };
}

/**
 * 檢查 finance + cashier 職責衝突
 */
export function hasRoleConflict(roleCodes) {
  return roleCodes.includes(ROLE_CODES.FINANCE) && roleCodes.includes(ROLE_CODES.CASHIER);
}
